### ISSUE TITLE
Synthetic Data from ResNet50

### ISSUE THREAD

**Issue by kcs6568** [VILA-Lab/SRe2L#12]
Hi. Thank you for providing such wonderful work.

In this project, the synthesized samples for the ImageNet-1K dataset are provided for only ResNet-18. 
So, I tried to generate the synthetic samples generated from ResNet50. But the runtime is too long so I cannot keep the generating work.
Do you have a plan that exports the synthetic samples generated from ResNet50?

For my research, the ResNet50 synthetic samples can be helpful so I want to be provided with those samples.

I'm looking forward to your positive reply.

Thank you!

**Comment by zeyuanyin** [comment]
@kcs6568 Thanks for your interest. You can download ResNet50 synthetic samples from [sre2l_in1k_rn50_2k_ipc50.zip](https://huggingface.co/datasets/zeyuanyin/SRe2L/resolve/main/sre2l_in1k_rn50_2k_ipc50.zip), which are recovered from ResNet50 with 2,000 iterations.

**Comment by kcs6568** [comment]
Oh, I didn't look more closely. Sorry!

Thank you again for your nice work!
