### ISSUE TITLE
Pretrained model for the moified VIT 

### ISSUE THREAD

**Issue by zhangxin-xd** [VILA-Lab/SRe2L#18]
Thank you for sharing this amazing work!

I have some problems reproducing the VIT results in your paper. Could you kindly provide the pretrained VIT weights you used? It would help a lot.

I look forward to your positive response. ☺️

**Comment by zeyuanyin** [comment]
Thanks for your interest in our work. 

You can download the model weights and training log at https://huggingface.co/zeyuanyin/BN-ViT/tree/main.

**Comment by zhangxin-xd** [comment]
Thank you for your help!
