### ISSUE TITLE
BN parameters or Subset statistics

### ISSUE THREAD

**Issue by self-reward** [VILA-Lab/SRe2L#20]
Dear Author,

Thank you for your excellent work. I noticed that SRe2L approximates feature statistics mean and standard deviation using BN parameters. Is it possible to obtain this information by processing a subset of the original images through the network, similar to DeepInversion? Have you tried this approach?

Looking forward to your response.

**Comment by zeyuanyin** [comment]
It could be a viable strategy if the subset is representative enough to capture the essential statistics of the entire dataset.
