### ISSUE TITLE
What is temperature in this paper

### ISSUE THREAD

**Issue by BeCarefulOfYournaoke** [VILA-Lab/SRe2L#22]
I cannot find the Equation containing tempureture in this paper. Is it in Eq (8) to gegerate soft label of synthetic data or in Eq (9) to train the model on synthetic data?

**Comment by szq0214** [comment]
Hi @BeCarefulOfYournaoke we use 1.0 as the default temperature for soft label generation (in Eq 8), but you can adjust it during this stage if you'd prefer to apply a different value.
