### ISSUE TITLE
Where can I find the file 'rn18_bn0.01_[4K]_x_l2_x_tv.crop'?

### ISSUE THREAD

**Issue by muyangli17** [VILA-Lab/SRe2L#3]
I am trying running `train_FKD.py` with `train.sh`, but I did not find the file `rn18_bn0.01_[4K]_x_l2_x_tv.crop` for argument `--train-dir` in the dataset link(https://mbzuaiac-my.sharepoint.com/personal/zeyuan_yin_mbzuai_ac_ae/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fzeyuan%5Fyin%5Fmbzuai%5Fac%5Fae%2FDocuments%2Fproject%5Fshare%2FSRe2L&ga=1). Can you show me where I can find it?
Thank you zeyuanyin.

**Comment by muyangli17** [comment]
Sorry, I mistook the procedure. Such file will be created from the procedure _data_synthesis.py_, right?

**Comment by zeyuanyin** [comment]
For detailed dataset information, please refer to `Download` section of our project page at https://zeyuanyin.github.io/projects/SRe2L/#Download. 

You can use our provided synthetic datasets to reproduce our results or you can generate them step by step.
