### ISSUE TITLE
Pretrained checkpoint on tiny-imagenet

### ISSUE THREAD

**Issue by zhiheng-ma** [VILA-Lab/SRe2L#6]
Could you please upload the pretrained checkpoint on tiny-imagenet? Thanks.

**Comment by zeyuanyin** [comment]
Hi @ZhihengCV, we release the training code for tiny-imagenet at https://github.com/zeyuanyin/tiny-imagenet, and you can find the pretrained checkpoint at https://github.com/zeyuanyin/tiny-imagenet#model-zoo
